name: version and release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Create published JIRA release
        uses: darioblanco/jira-wizard@main
        with:
          app: ToDo
          host: ${{ secrets.JIRA_HOST }}
          email: ${{ secrets.JIRA_EMAIL }}
          apiToken: ${{ secrets.JIRA_API_TOKEN }}
          projectKey: COM
          issueRegex: ((?<!([A-Z]))[A-Z]+-\d+)
          version: ${{ steps.tag_version.outputs.new_tag }}
          draft: false
