name: ZAP Baseline Scan
on: [pull_request]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: start app
        run: npm run start:ci &
      - name: wait for app  
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:8888/'
          responseCode: 200
          timeout: 2000
          interval: 500
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'https://localhost:8888'
