on:
  workflow_dispatch:
  push:
        
jobs:
  version:
    runs-on: ubuntu-latest    
    steps:  
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: version cmd
        id: version
        run:  echo '::set-output name=PROVIDER_VERSION::git describe --abbrev=0 --tags'
      - name: output version from varbiable
        run: echo "the provider version is ${{ steps.version.outputs.PROVIDER_VERSION }}"
        
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - run: echo ${{ steps.get_version.outputs.version-without-v }}
